services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=conference_rating
      - DB_USERNAME=conference_user
      - DB_PASSWORD=local_password
      - JWT_SECRET=local_jwt_secret_for_development_only
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=conference_rating
      - POSTGRES_USER=conference_user
      - POSTGRES_PASSWORD=local_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
