apiVersion: apps/v1
kind: Deployment
metadata:
  name: wed-dashboard
  namespace: iv-develop
  labels:
    app: wed-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wed-dashboard
  template:
    metadata:
      labels:
        app: wed-dashboard
    spec:
      containers:
      - name: wed-dashboard
        image: your-registry/wed-dashboard:latest  # Replace with your actual registry
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "conference_rating"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: jwt-secret
        livenessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: wed-dashboard-service
  namespace: iv-develop
  labels:
    app: wed-dashboard
spec:
  selector:
    app: wed-dashboard
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wed-dashboard-ingress
  namespace: iv-develop
  labels:
    app: wed-dashboard
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - wed-dashboard.renvc.net
    secretName: wed-dashboard-tls
  rules:
  - host: wed-dashboard.renvc.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wed-dashboard-service
            port:
              number: 8080

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: iv-develop
  labels:
    app: wed-dashboard
type: Opaque
data:
  jwt-secret: eW91ci1zdXBlci1zZWN1cmUtand0LXNlY3JldC1mb3ItcHJvZHVjdGlvbg==  # base64: your-super-secure-jwt-secret-for-production
