apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wed-dashboard
  namespace: argocd
  labels:
    app: wed-dashboard
spec:
  project: default
  source:
    repoURL: https://github.com/IvanoAlvino/wed-dashboard.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: iv-develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
