apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: iv-develop
  labels:
    app: wed-dashboard
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wed-dashboard
      component: database
  template:
    metadata:
      labels:
        app: wed-dashboard
        component: database
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "conference_rating"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: iv-develop
  labels:
    app: wed-dashboard
    component: database
spec:
  selector:
    app: wed-dashboard
    component: database
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: iv-develop
  labels:
    app: wed-dashboard
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: your-storage-class  # Uncomment and adjust if needed

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: iv-develop
  labels:
    app: wed-dashboard
    component: database
type: Opaque
data:
  username: Y29uZmVyZW5jZV91c2Vy  # base64: conference_user
  password: cG9zdGdyZXNfcGFzc3dvcmQ=  # base64: postgres_password
