# Production configuration for Railway deployment
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  # Disable problematic autoconfiguration classes
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration
        
# Optimized logging for production
logging:
  level:
    root: INFO
    com.wearedevelopers: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Completely disable Spring Boot Actuator for Railway deployment
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: false
  metrics:
    enable:
      root: false
    export:
      defaults:
        enabled: false
