# Production configuration for Railway deployment
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        
# Optimized logging for production
logging:
  level:
    root: INFO
    com.wearedevelopers: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Production actuator settings optimized for Railway
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
  metrics:
    enable:
      # Disable system metrics that cause container issues
      system: false
      process: false
      jvm: false
  # Disable automatic metric collection that fails in containers
  metric:
    export:
      simple:
        enabled: false
